[program:browser-manager]
command=/usr/local/bin/browser-manager.sh health-check
directory=/tmp
autostart=true
autorestart=true
priority=200
stderr_logfile=/var/log/supervisor/browser-manager.err.log
stdout_logfile=/var/log/supervisor/browser-manager.out.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile_backups=10
user=root
startsecs=10
startretries=3
killasgroup=true
stopasgroup=true
environment=REMOTE_DEBUG_PORT="9222",CHROME_USER_DATA_DIR="%(ENV_CHROME_USER_DATA_DIR)s",DISPLAY="%(ENV_DISPLAY)s"



