[program:novnc-server]
command=/usr/local/bin/start-novnc.sh
autostart=true
autorestart=true
priority=300
stderr_logfile=/var/log/supervisor/novnc-server.err.log
stdout_logfile=/var/log/supervisor/novnc-server.out.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile_backups=10
user=root
startsecs=10
startretries=3
killasgroup=true
stopasgroup=true
environment=VNC_PORT="%(ENV_VNC_PORT)s",NOVNC_PORT="%(ENV_NOVNC_PORT)s",NOVNC_HOME="%(ENV_NOVNC_HOME)s"
