[unix_http_server]
file=/tmp/supervisor.sock   ; path to the socket file
chmod=0700                 ; socket file permissions

[supervisord]
logfile=/var/log/supervisor/supervisord.log ; main log file
logfile_maxbytes=50MB        ; max log file size
logfile_backups=10           ; number of log backups
loglevel=info                ; log level
pidfile=/var/run/supervisord.pid ; PID file path
nodaemon=true                ; run in the foreground
silent=false                 ; don't suppress startup output
minfds=1024                  ; minimum file descriptors
minprocs=200                 ; minimum processes
user=root                    ; run as this user

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock ; connect via the unix socket

[include]
files = /etc/supervisor/conf.d/*.conf
