[unix_http_server]
file=/tmp/supervisor.sock   ; socket 文件的路径
chmod=0700                 ; socket 文件权限

[supervisord]
logfile=/var/log/supervisor/supervisord.log ; 主日志文件
logfile_maxbytes=50MB        ; 最大日志文件大小
logfile_backups=10           ; 日志文件备份数量
loglevel=info                ; 日志级别
pidfile=/var/run/supervisord.pid ; PID文件路径
nodaemon=true                ; 前台运行
silent=false                 ; 启动时不静默
minfds=1024                  ; 最小文件描述符
minprocs=200                 ; 最小进程数
user=root                    ; 运行用户

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock ; 使用 unix socket 连接

[include]
files = /etc/supervisor/conf.d/*.conf
